# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'envv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import shelve


class Env_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(299, 210)
        Dialog.setMinimumSize(QtCore.QSize(299, 210))
        Dialog.setMaximumSize(QtCore.QSize(299, 210))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/img/assets/road.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet('font: 8pt "Segoe UI";')
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(60, 10, 181, 21))
        self.label_6.setStyleSheet('font: 700 14pt "Segoe UI";')
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 180, 141, 21))
        self.pushButton.setMinimumSize(QtCore.QSize(141, 21))
        self.pushButton.setMaximumSize(QtCore.QSize(141, 21))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet(
            "QPushButton{\n"
            "border-radius:5px;\n"
            "color:rgb(239, 239, 239);\n"
            'font: 10pt "Gill Sans MT";\n'
            "background-color: rgb(99,99, 99);\n"
            "}\n"
            "QPushButton:hover {\n"
            "color:rgb(9, 9, 9);\n"
            "background-color:rgb(239, 239, 239);\n"
            "}\n"
            "QPushButton:pressed {\n"
            "color:rgb(9, 9, 9);\n"
            "}"
        )
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.write_db(Dialog))
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 281, 129))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setStyleSheet("height:13px;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.env_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.env_name.setObjectName("env_name")
        self.verticalLayout.addWidget(self.env_name)
        self.v_wind = QtWidgets.QLineEdit(self.layoutWidget)
        self.v_wind.setObjectName("v_wind")
        self.verticalLayout.addWidget(self.v_wind)
        self.incline = QtWidgets.QLineEdit(self.layoutWidget)
        self.incline.setObjectName("incline")
        self.verticalLayout.addWidget(self.incline)
        self.ro_air = QtWidgets.QLineEdit(self.layoutWidget)
        self.ro_air.setObjectName("ro_air")
        self.verticalLayout.addWidget(self.ro_air)
        self.gi = QtWidgets.QLineEdit(self.layoutWidget)
        self.gi.setStyleSheet("height:13px;")
        self.gi.setObjectName("gi")
        self.verticalLayout.addWidget(self.gi)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Çevre"))
        self.label_6.setText(_translate("Dialog", "Çevresel Faktörler"))
        self.pushButton.setText(_translate("Dialog", "Bilgileri Yaz"))
        self.label_8.setText(_translate("Dialog", "Ortam ismi"))
        self.label.setText(_translate("Dialog", "Rüzgar hızı  (km/h)"))
        self.label_2.setText(_translate("Dialog", "Yol eğimi  (açı)"))
        self.label_3.setText(_translate("Dialog", "Hava yoğunluğu (kg/m^3)"))
        self.label_4.setText(_translate("Dialog", "Yer çekimi ivmesi (m/s^2)"))

    def write_db(self, Dialog):
        env_name = self.env_name.text()
        sublist = [
            float(self.v_wind.text()),
            float(self.incline.text()),
            float(self.ro_air.text()),
            float(self.gi.text()),
        ]
        print(sublist)
        print(env_name)
        db = shelve.open("environments.db")
        db[env_name] = sublist
        print(f"{env_name} added to db")
        db.close()
        Dialog.close()


import env_rc


# if __name__ == "__main__":
#     import sys

#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Env_Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
