# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gearboxx.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import shelve
import sys


class GearBox_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(328, 192)
        Dialog.setMinimumSize(QtCore.QSize(328, 192))
        Dialog.setMaximumSize(QtCore.QSize(328, 192))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/img/assets/gearbox2.jpg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        Dialog.setWindowIcon(icon)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 160, 141, 21))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet(
            "QPushButton{\n"
            "border-radius:5px;\n"
            "color:rgb(239, 239, 239);\n"
            'font: 10pt "Gill Sans MT";\n'
            "background-color: rgb(99,99, 99);\n"
            "}\n"
            "QPushButton:hover {\n"
            "color:rgb(9, 9, 9);\n"
            "background-color:rgb(239, 239, 239);\n"
            "}\n"
            "QPushButton:pressed {\n"
            "color:rgb(9, 9, 9);\n"
            "}"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(lambda: self.write_db(Dialog))
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(70, 10, 191, 21))
        self.label_16.setStyleSheet('font: 700 12pt "Segoe UI";')
        self.label_16.setObjectName("label_16")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 40, 307, 110))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(161, 0))
        self.label_11.setStyleSheet('font: 8pt "Segoe UI";')
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setMinimumSize(QtCore.QSize(120, 0))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setMinimumSize(QtCore.QSize(120, 0))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gearbox_name = QtWidgets.QLineEdit(self.widget)
        self.gearbox_name.setObjectName("gearbox_name")
        self.verticalLayout.addWidget(self.gearbox_name)
        self.gears = QtWidgets.QLineEdit(self.widget)
        self.gears.setObjectName("gears")
        self.verticalLayout.addWidget(self.gears)
        self.dif = QtWidgets.QLineEdit(self.widget)
        self.dif.setObjectName("dif")
        self.verticalLayout.addWidget(self.dif)
        self.drive_train_eff = QtWidgets.QLineEdit(self.widget)
        self.drive_train_eff.setObjectName("drive_train_eff")
        self.verticalLayout.addWidget(self.drive_train_eff)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Şanzıman"))
        self.pushButton_2.setText(_translate("Dialog", "Bilgileri Yaz"))
        self.label_16.setText(_translate("Dialog", "Şanzıman Parametreleri"))
        self.label_10.setText(_translate("Dialog", "Şanzıman ismi"))
        self.label_11.setText(
            _translate("Dialog", "Vites oranları (3.45,2,3 şeklinde)")
        )
        self.label_14.setText(_translate("Dialog", "Diferansiyel dişli oranı"))
        self.label_15.setText(_translate("Dialog", "Aktarma organları verimi"))

    def write_db(self, Dialog):
        gearbox_name = self.gearbox_name.text()
        gearbox_list = self.gears.text().split(",")
        sublist = [
            gearbox_list,
            float(self.dif.text()),
            float(self.drive_train_eff.text()),
        ]
        print(sublist)
        db = shelve.open("gearboxes.db")
        db[gearbox_name] = sublist
        print(f"{gearbox_name} added to db")
        db.close()
        Dialog.close()


import gearbox_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = GearBox_Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
