# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vehiclee.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import shelve


class Vehicle_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 253)
        Dialog.setMinimumSize(QtCore.QSize(350, 253))
        Dialog.setMaximumSize(QtCore.QSize(350, 253))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/img/assets/vehicle.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        Dialog.setWindowIcon(icon)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 220, 141, 21))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet(
            "QPushButton{\n"
            "border-radius:5px;\n"
            "color:rgb(239, 239, 239);\n"
            'font: 10pt "Gill Sans MT";\n'
            "background-color: rgb(99,99, 99);\n"
            "}\n"
            "QPushButton:hover {\n"
            "color:rgb(9, 9, 9);\n"
            "background-color:rgb(239, 239, 239);\n"
            "}\n"
            "QPushButton:pressed {\n"
            "color:rgb(9, 9, 9);\n"
            "}"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(lambda: self.write_db(Dialog))
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(100, 10, 151, 21))
        self.label_16.setStyleSheet('font: 700 12pt "Segoe UI";')
        self.label_16.setObjectName("label_16")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 41, 331, 166))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(161, 0))
        self.label_11.setStyleSheet('font: 8pt "Segoe UI";')
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setMinimumSize(QtCore.QSize(120, 0))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setMinimumSize(QtCore.QSize(120, 0))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setMinimumSize(QtCore.QSize(120, 0))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setMinimumSize(QtCore.QSize(120, 0))
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        #######################################################################
        self.vehicle_name = QtWidgets.QLineEdit(self.widget)
        self.vehicle_name.setObjectName("vehicle_name")
        #######################################################################
        self.verticalLayout.addWidget(self.vehicle_name)
        #######################################################################
        self.m_vehicle = QtWidgets.QLineEdit(self.widget)
        self.m_vehicle.setObjectName("m_vehicle")
        #######################################################################
        self.verticalLayout.addWidget(self.m_vehicle)
        #######################################################################
        self.cf = QtWidgets.QLineEdit(self.widget)
        self.cf.setObjectName("cf")
        #######################################################################
        self.verticalLayout.addWidget(self.cf)
        #######################################################################
        self.af = QtWidgets.QLineEdit(self.widget)
        self.af.setObjectName("af")
        #######################################################################
        self.verticalLayout.addWidget(self.af)
        #######################################################################
        self.roll_c = QtWidgets.QLineEdit(self.widget)
        self.roll_c.setObjectName("roll_c")
        #######################################################################
        self.verticalLayout.addWidget(self.roll_c)
        #######################################################################
        self.eff_r = QtWidgets.QLineEdit(self.widget)
        self.eff_r.setObjectName("eff_r")
        #######################################################################
        self.verticalLayout.addWidget(self.eff_r)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Araç"))
        self.pushButton_2.setText(_translate("Dialog", "Bilgileri Yaz"))
        self.label_16.setText(_translate("Dialog", "Araç Parametreleri"))
        self.label_10.setText(_translate("Dialog", "Araç ismi"))
        self.label_11.setText(_translate("Dialog", "Araç kütlesi (kg)"))
        self.label_14.setText(_translate("Dialog", "Cf aerodinamik direnç katsayısı"))
        self.label_15.setText(_translate("Dialog", "Af araç izdüşüm alanı (m^2)"))
        self.label_17.setText(_translate("Dialog", "Yuvarlanma direnç katsayısı"))
        self.label_18.setText(_translate("Dialog", "Tekerlek efektif yarıçapı (m)"))

    def write_db(self, Dialog):
        vehicle_name = self.vehicle_name.text()
        sublist = [
            float(self.m_vehicle.text()),
            float(self.cf.text()),
            float(self.af.text()),
            float(self.roll_c.text()),
            float(self.eff_r.text()),
        ]
        db = shelve.open("vehicles.db")
        db[vehicle_name] = sublist
        print(f"{vehicle_name} added to db")
        db.close()
        Dialog.close()


import vehicle_rc


# if __name__ == "__main__":
#     import sys

#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Vehicle_Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
